Repository andritowmega/fastmvp, pull requests merged in 2024-12, with the labels that each got.

#46 DOC :memo: project information
  readme.md
Labels: documentation

#47 feat: resolve code smells in app
  app.js
  bin/www
  config/postgresdb.js
  fastmvpcore/routes/api.js
  fastmvpcore/routes/view.js
  fastmvpcore/services/allfunctions.service.js
  fastmvpcore/utils/functions.js
  routes/index.js
Labels: code smell

#48 Feat unit test
  package-lock.json
  package.json
  test/utils/auth.test.js
  test/utils/functions.test.js
  test/utils/toassemble.test.js
Labels: enhancement
